[package]
name = "oxidarr-ui"
description = "Dioxus frontend for Oxidarr apps"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "oxidarr_ui"
path = "src/lib.rs"

[[bin]]
name = "oxidarr-ui"
path = "src/main.rs"

[dependencies]
dioxus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
