[package]
name = "oxidarr-cardigann"
description = "Cardigann v11 indexer definition engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
oxidarr-core = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
fancy-regex = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
